kind: pipeline
name: default

steps:
- name: build
  image: openjdk:11
  commands:
  - ./gradlew clean build
  - "echo 10 most recent commits: > note.txt"
  - "git log --pretty=tformat:%B -n10 >> note.txt"
  - "rm build/libs/*-dev.jar"
- name: release
  image: mac89/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: Dev Build
    prerelease: true
    tag: dev
    note: note.txt
    allow_edit: true
  when:
    branch:
    - trunk
